### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by hanneslehmann** [jbn/IPlantUML#3]
Hi,

maybe you can help - I get following error:
```
pip2 install iplantuml
Collecting iplantuml
  Using cached IPlantUML-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wli4gI/iplantuml/setup.py", line 18
        print(line, end='')
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wli4gI/iplantuml/
```

I have to use pip2 as I have python3 as well on my system.

**Comment by jbn** [comment]
bfffee6da1b93d0aec74c should fix it. Just uploaded to pypi.

Give:

```pip2 install iplantuml --no-cache-dir```

a try and LMK if it worked.

**Comment by hanneslehmann** [comment]
hmmm, tried with and without "--no-cache-dir" but still getting errors (both shown below): 

```
>sudo -H pip2 install iplantuml --no-cache-dir
[sudo] Passwort für hannes: 
Collecting iplantuml
  Downloading IPlantUML-0.0.4.tar.gz
Installing collected packages: iplantuml
  Running setup.py install for iplantuml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jr7JJ9/iplantuml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ysc6pn-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jr7JJ9/iplantuml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ysc6pn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jr7JJ9/iplantuml/


> sudo -H pip2 install iplantuml               
Collecting iplantuml
  Downloading IPlantUML-0.0.4.tar.gz
Building wheels for collected packages: iplantuml
  Running setup.py bdist_wheel for iplantuml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Hk05R8/iplantuml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8wMCCtpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/iplantuml
  copying iplantuml/__init__.py -> build/lib.linux-x86_64-2.7/iplantuml
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Hk05R8/iplantuml/setup.py", line 48, in <module>
      cmdclass={'install':InstallCommand},
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 182, in run
      reinit_subcommands=True)
    File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 136, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "/usr/lib/python2.7/distutils/cmd.py", line 319, in reinitialize_command
      command, reinit_subcommands)
    File "/usr/lib/python2.7/distutils/dist.py", line 925, in reinitialize_command
      command = self.get_command_obj(command_name)
    File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
    File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 132, in __init__
      _Command.__init__(self, dist)
    File "/usr/lib/python2.7/distutils/cmd.py", line 64, in __init__
      self.initialize_options()
    File "/tmp/pip-build-Hk05R8/iplantuml/setup.py", line 26, in initialize_options
      super().initialize_options()
  TypeError: super() takes at least 1 argument (0 given)
  
  ----------------------------------------
  Failed building wheel for iplantuml
  Running setup.py clean for iplantuml
Failed to build iplantuml
Installing collected packages: iplantuml
  Running setup.py install for iplantuml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Hk05R8/iplantuml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3858aB-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Hk05R8/iplantuml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3858aB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Hk05R8/iplantuml/

**Comment by jbn** [comment]
Sorry, @hanneslehmann! Crazy delayed, but it should work now.
